# Generated by Django 3.1 on 2023-11-23 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20231118_1812'),
        ('contacts', '0002_auto_20231122_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.listing'),
        ),
    ]
