# Generated by Django 3.1 on 2023-11-27 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20231123_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.IntegerField(primary_key=True),
        ),
    ]
