# Generated by Django 3.1 on 2023-12-03 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20231127_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_date',
            new_name='contact_date_end',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_date_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
