# Generated by Django 3.1 on 2023-12-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20231204_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactbackup',
            name='appointment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
