# Generated by Django 3.1 on 2023-09-13 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listing',
            table='listing_listing',
        ),
    ]
