# Generated by Django 3.1 on 2023-11-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_auto_20231107_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(default='photos/image/noIMG.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
