# Generated by Django 3.1 on 2023-12-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerCmd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
