# Generated by Django 3.1 on 2023-12-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerCmd', '0004_reply_parent_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='parent_reply',
        ),
    ]
