# Generated by Django 3.1 on 2023-11-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileOTP', '0003_profile_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qr_code_image',
            field=models.ImageField(null=True, upload_to='photos/qrcode/'),
        ),
    ]
