# Generated by Django 3.1 on 2023-12-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileOTP', '0004_auto_20231129_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_qr_code_scanned',
            field=models.BooleanField(default=False),
        ),
    ]
