# Generated by Django 3.1 on 2023-11-21 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
