# Generated by Django 3.1 on 2023-11-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20231127_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
