# Generated by Django 3.1 on 2023-11-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(default=None, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
